---
- name: Converge
  hosts: all
  tasks:
    - name: "Include Ansible role"
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      tags:
        - docker
        - checkpoint_waf_agent
