---
collections:
    - name: community.general
      version: 12.4.0
    - name: community.docker
      version: 5.0.6
roles:
    - name: docker_rootless
      src: https://github.com/konstruktoid/ansible-role-docker-rootless.git
      version: v1.11.0
      scm: git
