---
collections:
    - name: community.general
      version: 12.6.1
    - name: community.docker
      version: 5.2.0
    - name: ansible.posix
      version: 2.1.0
roles:
    - name: docker_rootless
      src: https://github.com/konstruktoid/ansible-role-docker-rootless.git
      version: v1.20.0
      scm: git
