---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Verify service ports
      ansible.builtin.include_role:
        name: tests/diffusion_tests
      vars:
        verify_ports:
          - port: 8443
            description: "HTTPS port"
          - port: 8080
            description: "HTTP port"
          - port: 8117
            description: "Checkpoint nano agent health port."
    - name: Test Docker containers
      ansible.builtin.include_role:
        name: tests/diffusion_tests
      vars:
        docker_user: "{{ docker_user }}"
        verify_docker_containers:
          - name: "cp_waf_agent"
            state: "running"
            image: "{{ docker_full_image_path }}"
