---
name: Tests

on:
  pull_request:
  workflow_dispatch:
    scenario:
      description: "Which scenario(s) to run"
      type: choice
      options:
        - all
        - default
        - multi
      default: all

jobs:
  test:
    name: Molecule Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - scenario: default
          - scenario: multi
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add user
        run: |
          sudo useradd -m /bin/bash docker-adm

      - name: Run Diffusion Tests for Scenario ${{ matrix.scenario }}
        uses: Polar-Team/diffusion/diffusion-test@main
        with:
          diffusion-version: "latest"
          scenario: "${{ matrix.scenario }}"
          run-lint: "true"
          run-verify: "true"
          run-idempotence: "true"
          cache-enabled: "true"
          cache-uv: "true"
          cache-docker: "true"
